basePath: /api
host: localhost:8080
info:
  contact: {}
  description: Todo API Documentation. Written in Go. Gin used
  title: Todo API
  version: "1.0"
paths:
  /todos:
    get:
      description: Fetch todos from DB
      produces:
      - application/json
      responses: {}
      summary: Get todos
      tags:
      - tags
swagger: "2.0"
